# custom sequence
sequence = ["shell", "latex", "biblatex", "latex", "latex"]

# select source
source = "thesis.tex"

# shell
[programs.shell]
command = "bash"
args = "svg2pdf.sh"

# latex
[programs.latex]
command = "pdflatex"
args = "%T"

# biblatex
[programs.biblatex]
command = "biber"
args = "%B.bcf"
