# custom sequence
sequence = ["shell", "latex", "latex"]

# select source
source = "slide.tex"

# shell
[programs.shell]
command = "bash"
args = "svg2pdf.sh"

# latex
[programs.latex]
command = "pdflatex"
args = "%T"